title: Shariff Sarip-Abidinsa
description: Data Analytics & AI · SupTech/RegTech · AML/CFT

author:
  name: Shariff Sarip-Abidinsa
  email: sbinsari@andrew.cmu.edu

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
