title: Shariff Sarip-Abidinsa
description: Data & AI • SupTech/RegTech • AML/CFT Analytics
author:
  name: Shariff Sarip-Abidinsa
  email: sbinsari@andrew.cmu.edu
  github: shariffsa
# Use GitHub Pages supported theme
theme: minima

# Show pages in the header nav (by filename)
header_pages:
  - about.md
  - projects.md
  - resume.md
  - contact.md

# Minima options
minima:
  social_links:
    - {"platform": "github", "user_url": "https://github.com/shariffsa"}
    - {"platform": "linkedin", "user_url": "https://www.linkedin.com/in/shariffsarip/"}
    - {"platform": "x", "user_url": "https://x.com/shariff_ai"}

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you later set a custom domain, uncomment the next line and set it
# url: https://www.YOURDOMAIN.com

# Useful defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
